# databases:
#   - name: finmako
#     databaseName: finmako
#     user: finmako

services:
  - type: web
    name: finmako
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn fintools.wsgi:application"
    envVars:
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: finmako
      #     property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4